// export default {
//   play: require("../assets/icons/pawn.svg"),
//   scan: require("../assets/icons/qrcode.svg"),
//   storage: require("../assets/icons/box.svg"),
// };

export default {
  play: require("../assets/icons/pawn.png"),
  scan: require("../assets/icons/qrcode.png"),
  storage: require("../assets/icons/box.png"),
  no_camera: require("../assets/icons/no_camera.png"),
  camera: require("../assets/icons/camera.png"),
  flash_off: require("../assets/icons/flash_off.png"),
  flash_on: require("../assets/icons/flash_on.png"),
  gallery: require("../assets/icons/gallery.png"),
  help: require("../assets/icons/help.png"),
  scan_button: require("../assets/icons/scan_button.png"),
  settings: require("../assets/icons/settings.png"),
  hourglass: require("../assets/icons/hourglass.png"),
  preset_custom: require("../assets/icons/preset_custom.png"),
  preset_bullet: require("../assets/icons/preset_bullet.png"),
  preset_rapid: require("../assets/icons/preset_rapid.png"),
  preset_standard: require("../assets/icons/preset_standard.png"),
  plus: require("../assets/icons/plus.png"),
  plus_thick: require("../assets/icons/plus_thick.png"),
  cross: require("../assets/icons/cross.png"),
  clock_lines: require("../assets/icons/clock_lines.png"),
  clock_full: require("../assets/icons/clock_full.png"),
  arrow_left: require("../assets/icons/arrow_left.png"),
  check: require("../assets/icons/check.png"),
};